# Generated by Django 2.2.5 on 2019-11-10 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradesApp', '0007_delete_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds', models.IntegerField()),
                ('dld', models.IntegerField()),
                ('dm', models.IntegerField()),
                ('la', models.IntegerField()),
                ('stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradesApp.Student')),
            ],
        ),
    ]
